apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-soft-affinity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-soft
  template:
    metadata:
      labels:
        app: my-app-soft
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - on-demand
                      - spot
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - my-app-soft  # Avoids placing soft affinity pods on the same node
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80
